# Regressão Linear

## Importação de bibliotecas

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Carregar dataframe

In [42]:
dataframe = pd.read_csv('Crime_Data_from_2020_to_Present.csv', sep=';')

In [43]:
dataframe.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 00:00,03/01/2020 00:00,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,340.375,-1.183.506
1,200106753,02/09/2020 00:00,02/08/2020 00:00,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,340.444,-1.182.628
2,200320258,11/11/2020 00:00,11/04/2020 00:00,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.021,-1.183.002
3,200907217,05/10/2023 00:00,03/10/2020 00:00,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,341.576,-1.184.387
4,220614831,08/18/2022 12:00:00 AM,08/17/2020 12:00:00 AM,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,340.944,-1.183.277

In [62]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955339 entries, 0 to 955338
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           955339 non-null  int64
 1   Date Rptd       955339 non-null  object
 2   DATE OCC        955339 non-null  object
 3   TIME OCC        955339 non-null  int64
 4   AREA            955339 non-null  int64
 5   AREA NAME       955339 non-null  object
 6   Rpt Dist No     955339 non-null  int64
 7   Part 1-2        955339 non-null  int64
 8   Crm Cd          955339 non-null  int64
 9   Crm Cd Desc     955339 non-null  object
 10  Mocodes         818664 non-null  object
 11  Vict Age        955339 non-null  int64
 12  Vict Sex        825294 non-null  object
 13  Vict Descent    825284 non-null  object
 14  Premis Cd       955327 non-null  float64
 15  Premis Desc     954770 non-null  object
 16  Weapon Used Cd  325019 non-null  float64
 17  Weapon Desc     325019 non-null  object
 18  Status          955338 non-null  object
 19  Status Desc     955339 non-null  object
 20  Crm Cd 1        955328 non-null  float64
 21  Crm Cd 2        68466 non-null   float64
 22  Crm Cd 3        2294 non-null    float64
 23  Crm Cd 4        64 non-null      float64
 24  LOCATION        955339 non-null  object
 25  Cross Street    148900 non-null  object
 26  LAT             955339 non-null  float64
 27  LON             955339 non-null  object
dtypes: float64(7), int64(7), object(14)
memory usage: 204.1+ MB

## Descrição das colunas do dataset

### Colunas e Tipos de Dados

In [23]:
data_dict = {
    'Column': [
        'DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME', 'Rpt Dist No',
        'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes', 'Vict Age', 'Vict Sex',
        'Vict Descent', 'Premis Cd', 'Premis Desc', 'Weapon Used Cd', 'Weapon Desc',
        'Status', 'Status Desc', 'Crm Cd 1', 'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4',
        'LOCATION', 'Cross Street', 'LAT', 'LON'
    ],
    'Description': [
        'Identificador do registro', 'Data do relatório', 'Data da ocorrência',
        'Hora da ocorrência', 'Área numérica', 'Nome da área', 'Número do distrito de relatório',
        'Parte do crime', 'Código do crime', 'Descrição do código do crime',
        'Códigos de modos de operação', 'Idade da vítima', 'Sexo da vítima',
        'Ancestralidade da vítima', 'Código do local', 'Descrição do local',
        'Código da arma utilizada', 'Descrição da arma utilizada', 'Status do caso',
        'Descrição do status', 'Código do crime 1', 'Código do crime 2', 'Código do crime 3',
        'Código do crime 4', 'Localização do crime', 'Rua cruzada', 'Latitude', 'Longitude'
    ],
    'Dtype': [
        'int64', 'object', 'object', 'int64', 'int64', 'object', 'int64',
        'int64', 'int64', 'object', 'object', 'int64', 'object', 'object',
        'float64', 'object', 'float64', 'object', 'object', 'object',
        'float64', 'float64', 'float64', 'float64', 'object', 'object', 'float64', 'float64'
    ]
}


description_df = pd.DataFrame(data_dict)
description_df

            Column                      Description    Dtype
0            DR_NO        Identificador do registro    int64
1        Date Rptd                Data do relatório   object
2         DATE OCC               Data da ocorrência   object
3         TIME OCC               Hora da ocorrência    int64
4             AREA                    Área numérica    int64
5        AREA NAME                     Nome da área   object
6      Rpt Dist No  Número do distrito de relatório    int64
7         Part 1-2                   Parte do crime    int64
8           Crm Cd                  Código do crime    int64
9      Crm Cd Desc     Descrição do código do crime   object
10         Mocodes     Códigos de modos de operação   object
11        Vict Age                  Idade da vítima    int64
12        Vict Sex                   Sexo da vítima   object
13    Vict Descent         Ancestralidade da vítima   object
14       Premis Cd                  Código do local  float64
15     Premis Desc               Descrição do local   object
16  Weapon Used Cd         Código da arma utilizada  float64
17     Weapon Desc      Descrição da arma utilizada   object
18          Status                   Status do caso   object
19     Status Desc              Descrição do status   object
20        Crm Cd 1                Código do crime 1  float64
21        Crm Cd 2                Código do crime 2  float64
22        Crm Cd 3                Código do crime 3  float64
23        Crm Cd 4                Código do crime 4  float64
24        LOCATION             Localização do crime   object
25    Cross Street                      Rua cruzada   object
26             LAT                         Latitude  float64
27             LON                        Longitude  float64

In [31]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955339 entries, 0 to 955338
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           955339 non-null  int64
 1   Date Rptd       955339 non-null  object
 2   DATE OCC        955339 non-null  object
 3   TIME OCC        955339 non-null  int64
 4   AREA            955339 non-null  int64
 5   AREA NAME       955339 non-null  object
 6   Rpt Dist No     955339 non-null  int64
 7   Part 1-2        955339 non-null  int64
 8   Crm Cd          955339 non-null  int64
 9   Crm Cd Desc     955339 non-null  object
 10  Mocodes         818664 non-null  object
 11  Vict Age        955339 non-null  int64
 12  Vict Sex        825294 non-null  object
 13  Vict Descent    825284 non-null  object
 14  Premis Cd       955327 non-null  float64
 15  Premis Desc     954770 non-null  object
 16  Weapon Used Cd  325019 non-null  float64
 17  Weapon Desc     325019 non-null  object
 18  Status          955338 non-null  object
 19  Status Desc     955339 non-null  object
 20  Crm Cd 1        955328 non-null  float64
 21  Crm Cd 2        68466 non-null   float64
 22  Crm Cd 3        2294 non-null    float64
 23  Crm Cd 4        64 non-null      float64
 24  LOCATION        955339 non-null  object
 25  Cross Street    148900 non-null  object
 26  LAT             955339 non-null  float64
 27  LON             955339 non-null  object
dtypes: float64(7), int64(7), object(14)
memory usage: 204.1+ MB

## Limpeza dos dados

Podemos identificar que se faz necessário um tratamento de dados pois temos alguns problemas em nosso dataset, alguns deles são:
* Tipos incorretos de dados
* Ausência de dados
* formatação de dados

#### Tarefa 1 - Ajustar tipos de dados

In [ ]:
def extrair_data(data_str):
    partes = data_str.split(' ')
    data = partes[0]
    return data

In [ ]:
dataframe['Date Rptd'] = dataframe['Date Rptd'].apply(extrair_data)
dataframe['DATE OCC'] = dataframe['DATE OCC'].apply(extrair_data)

In [63]:
# 1. Ajustar tipos de dados
dataframe['Date Rptd'] = pd.to_datetime(dataframe['Date Rptd'], errors='coerce')
dataframe['DATE OCC'] = pd.to_datetime(dataframe['DATE OCC'], errors='coerce')

In [64]:
dataframe.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,2020-03-01,2020-03-01,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,340.375,-1.183.506
1,200106753,2020-02-09,2020-02-08,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,340.444,-1.182.628
2,200320258,2020-11-11,2020-11-04,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.021,-1.183.002
3,200907217,2023-05-10,2020-03-10,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,341.576,-1.184.387
4,220614831,2022-08-18,2020-08-17,1200,6,Hollywood,666,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,1900 TRANSIENT,NaN,340.944,-1.183.277

#### Tarefa 2 - Obter a quantidade total de registros vazios por feature

In [35]:
print(dataframe.isnull().sum())

DR_NO                  0
Date Rptd         572373
DATE OCC          562639
TIME OCC               0
AREA                   0
AREA NAME              0
Rpt Dist No            0
Part 1-2               0
Crm Cd                 0
Crm Cd Desc            0
Mocodes           136675
Vict Age               0
Vict Sex          130045
Vict Descent      130055
Premis Cd             12
Premis Desc          569
Weapon Used Cd    630320
Weapon Desc       630320
Status                 1
Status Desc            0
Crm Cd 1              11
Crm Cd 2          886873
Crm Cd 3          953045
Crm Cd 4          955275
LOCATION               0
Cross Street      806439
LAT                    0
LON                    0
dtype: int64

#### Tarefa 3 - Remover espaços em excesso

In [36]:
dataframe['LOCATION'] = dataframe['LOCATION'].str.strip()
dataframe['Cross Street'] = dataframe['Cross Street'].str.strip()

In [65]:
print(dataframe.info())
# df.to_csv('dataset_tratado.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955339 entries, 0 to 955338
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           955339 non-null  int64
 1   Date Rptd       955339 non-null  datetime64[ns]
 2   DATE OCC        955339 non-null  datetime64[ns]
 3   TIME OCC        955339 non-null  int64
 4   AREA            955339 non-null  int64
 5   AREA NAME       955339 non-null  object
 6   Rpt Dist No     955339 non-null  int64
 7   Part 1-2        955339 non-null  int64
 8   Crm Cd          955339 non-null  int64
 9   Crm Cd Desc     955339 non-null  object
 10  Mocodes         818664 non-null  object
 11  Vict Age        955339 non-null  int64
 12  Vict Sex        825294 non-null  object
 13  Vict Descent    825284 non-null  object
 14  Premis Cd       955327 non-null  float64
 15  Premis Desc     954770 non-null  object
 16  Weapon Used Cd  325019 non-null  float64
 17  Weapon Desc     325019 non-null  object
 18  Status          955338 non-null  object
 19  Status Desc     955339 non-null  object
 20  Crm Cd 1        955328 non-null  float64
 21  Crm Cd 2        68466 non-null   float64
 22  Crm Cd 3        2294 non-null    float64
 23  Crm Cd 4        64 non-null      float64
 24  LOCATION        955339 non-null  object
 25  Cross Street    148900 non-null  object
 26  LAT             955339 non-null  float64
 27  LON             955339 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(7), object(12)
memory usage: 204.1+ MB
None

In [67]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score



# Definindo as variáveis independentes (X) e a variável dependente (y)
X = dataframe[['AREA', 'TIME OCC']]  # Variáveis independentes
y = dataframe['Vict Age']  # Variável dependente

# Dividindo os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Criando e treinando o modelo de regressão linear
modelo = LinearRegression()
modelo.fit(X_train, y_train)

# Fazendo previsões
y_pred = modelo.predict(X_test)

# Avaliando o modelo
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 478.5478685754589
R^2 Score: 0.0018427176413868818